#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.
CONF="\
frontend striker_balancer
    bind *:80
    mode http
    default_backend striker
backend striker
    balance roundrobin
    server 138091-web-01 52.90.14.254:80 check
    server 138091-web-02 100.25.21.178:80 check
"
sudo apt-get -y update
sudo apt-get -y install haproxy
sudo echo "ENABLED=1" >> /etc/default/haproxy
sudo echo "$CONF" >> /etc/haproxy/haproxy.cfg
sudo service haproxy start
