#!/usr/bin/env bash
# Bash script that displays: To infinity and beyond indefinitely I am invincible!!! when receiving a SIGTERM signal

echo "$$" > /var/run/holbertonscript.pid
trap "echo 'I hate the kill command'; rm /var/run/holbertonscript.pid; exit" SIGTERM
trap "rm /var/run/holbertonscript.pid; exit" SIGQUIT 
trap "echo 'Y U no love me?!'" SIGINT 
while :
do
   echo 'To infinity and beyond'
   sleep 2

done
