#!/usr/bin/env bash
# displays numbers from 1 to 100.Displays FizzBuzz when the number is a multiple of 3 and 5, Fizz when is multiple of 3 Buzz when is a multiple of 5
for x in {1..100}
do
     if [ $((x % 3)) == 0 ] && [ $((x % 5)) == 0 ]
     then
             echo "FizzBuzz"
     elif [ $((x % 3)) == 0 ]
     then
             echo "Fizz"
     elif [ $((x % 5)) == 0 ]
     then
             echo "Buzz"
     else
             echo $x
     fi
done
