#!/usr/bin/env bash
#  displays numbers from 1 to 20 and 4: bad luck from China, 9: bad luck from Japan,  17: bad luck from Italy for the 17th loop iteration
x=1
while [ $x -le 20 ]
do
     case $x in
             4)
                 echo "$x"
                 echo "bad luck from China"
                 ;;
             9)
                 echo "$x"
                 echo "bad luck from Japan"
                 ;;
             17)
                 echo "$x"
                 echo "bad luck from Italy"
                 ;;  
             *)
                 echo "$x"
     esac        
     ((x++))
done
