#!/usr/bin/env bash
# gives you information about the school file. file exists, file does not exist, file is empty, file is not empty, is a regular file
file="./school"
if [ -e $file ]
then
     echo "school file exists"
     if [ -s $file ]
     then
             echo "school file is not empty"
     else
             echo "school file is empty"
     fi
     if [ -f $file ]
     then
             echo "school is a regular file"
     fi
else
     echo "school file does not exist"
fi    
