#!/usr/bin/env bash
#  to get Apache to run on the container and to return a page containing Hello Holberton when querying the root of it
apt-get install apache2 -y
echo "ServerName localhost" >> /etc/apache2/apache2.conf
/etc/init.d/apache2 start
