#!/usr/bin/env bash
# to connect to your server using the private key ~/.ssh/school with the user ubuntu.
# ssh -i ~/.ssh/school ubuntu@138091-web-01
ssh -i ~/.ssh/holberton ubuntu@54.146.71.226
# cat ~/.ssh/id_rsa.pub | ssh ubuntu@138091-web-01 "mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys"

